'use strict';
window.ConceptExplorers={
 mount(id,host){
  const $=s=>host.querySelector(s);
  if(id==='p03'){
   host.innerHTML='<section class="concept-explorer"><div class="eyebrow">CHANGE ONE THING · WATCH THE CONSEQUENCE</div><h2>A loop, one step at a time</h2><p>Predict the final total before stepping. Turn on the bug to see why an accumulator must survive between iterations.</p><label>Count up to <input id="loop-limit" type="range" min="1" max="8" value="4"><output id="loop-limit-label">4</output></label><label class="explorer-toggle"><input id="loop-bug" type="checkbox"> Introduce bug: reset total inside the loop</label><pre id="loop-program"></pre><div class="trace-values"><div>Current number<strong id="loop-current">—</strong></div><div>Total<strong id="loop-total">0</strong></div></div><div class="button-row"><button class="primary" id="loop-step">Next iteration</button><button class="secondary" id="loop-reset">Reset trace</button></div><p id="loop-message" role="status">Before the loop: no values have been visited, total is 0.</p></section>';
   let step=0,total=0;
   const paint=()=>{const n=Number($('#loop-limit').value),bug=$('#loop-bug').checked;$('#loop-limit-label').textContent=n;$('#loop-program').textContent=`total = 0\nfor number in range(1, ${n+1}):\n${bug?'    total = 0  # BUG: forgets earlier work\n':''}    total += number\nprint(total)`;$('#loop-current').textContent=step||'—';$('#loop-total').textContent=total;$('#loop-step').disabled=step>=n;};
   const reset=()=>{step=0;total=0;paint();$('#loop-message').textContent='Before the loop: no values have been visited, total is 0.';};
   $('#loop-step').onclick=()=>{const before=total;step++;if($('#loop-bug').checked)total=0;total+=step;paint();$('#loop-message').textContent=$('#loop-bug').checked?`Iteration ${step}: the old total ${before} was discarded. The new total is only ${total}.`:`Iteration ${step}: ${before} + ${step} = ${total}. Total summarizes every visited number.`;};$('#loop-reset').onclick=reset;$('#loop-limit').oninput=reset;$('#loop-bug').onchange=reset;paint();return;
  }
  if(id==='m05'){
   host.innerHTML='<section class="concept-explorer"><div class="eyebrow">SEE THE ROWS, NOT JUST THE SYNTAX</div><h2>Where did the missing customer go?</h2><p>Asha has two orders; Ravi has none. Change the join, then apply a filter to the right-hand table.</p><div class="explorer-inputs"><label>Join type <select id="join-type"><option>INNER</option><option>LEFT</option></select></label><label><input type="checkbox" id="join-filter"> Add WHERE orders.total &gt; 100</label></div><pre id="join-query"></pre><div class="table-scroll"><table><thead><tr><th>Customer</th><th>Order</th><th>Total</th></tr></thead><tbody id="join-rows"></tbody></table></div><p id="join-message" role="status"></p></section>';
   const paint=()=>{const left=$('#join-type').value==='LEFT',filter=$('#join-filter').checked;const rows=[['Asha',101,80],['Asha',102,200],...(left?[['Ravi',null,null]]:[])].filter(r=>!filter||(r[2]!==null&&r[2]>100));$('#join-query').textContent=`SELECT c.name, o.id, o.total\nFROM customers c\n${left?'LEFT':'INNER'} JOIN orders o ON o.customer_id = c.id${filter?'\nWHERE o.total > 100':''};`;$('#join-rows').innerHTML=rows.map(r=>'<tr>'+r.map(v=>`<td>${v===null?'<em>NULL</em>':v}</td>`).join('')+'</tr>').join('');$('#join-message').textContent=`${rows.length} result rows. `+(left&&filter?'The WHERE predicate rejects Ravi’s NULL-extended row. To preserve customers, reason about moving the order condition into ON.':left?'LEFT JOIN preserves Ravi with NULL order fields. Asha still appears twice because two orders match.':'INNER JOIN returns only matching orders. Count result rows separately from distinct customers.');};$('#join-type').onchange=paint;$('#join-filter').onchange=paint;paint();return;
  }
  if(id==='s07'){
   host.innerHTML='<section class="concept-explorer"><div class="eyebrow">MAKE FAILURE PART OF THE MODEL</div><h2>Choose the deployment baseline</h2><div class="commit-trace"><span>A<br><small>Deployed</small></span><b>→</b><span>B<br><small>Added field · failed deploy</small></span><b>→</b><span>C<br><small>Updated class · ready</small></span></div><label>Compare C against <select id="delta-base"><option value="B">B: previous commit</option><option value="A">A: last successful deployment</option></select></label><div id="delta-result" class="output" role="status"></div><p>Model assumption: both changes are intended for this target and the pipeline tracks its last successful deployment. Real delta tooling also needs dependencies, deletions and adequate Git history.</p></section>';
   const paint=()=>{$('#delta-result').textContent=$('#delta-base').value==='A'?'A → C includes both the field introduced at B and the class update at C. The target can receive the cumulative intended change.':'B → C includes the class update only. The target never received B’s field: this comparison silently omits needed work.';};$('#delta-base').onchange=paint;paint();return;
  }
  host.remove();
 }
};
