'use strict';
window.FirstSteps=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function mount(id,host){
  if(!host)return;
  const intro='<div class="eyebrow">TRY ONE TINY EXPERIMENT</div>';
  if(id==='py-first'){
   let step=0;
   host.innerHTML=intro+'<h3>Walk through two instructions</h3><p>Choose a name, guess what the greeting will say, then follow one line at a time.</p><label for="demo-name">Name in this example</label><input id="demo-name" maxlength="25" value="Asha" autocomplete="off"><div id="trace-code" class="trace-code"></div><div class="demo-values"><div><span>What the name remembers</span><strong id="trace-name">Not assigned yet</strong></div><div><span>What appears on the screen</span><strong id="trace-output">Nothing printed yet</strong></div></div><p id="trace-status" class="demo-status" role="status" aria-live="polite">Before line 1. What do you predict?</p><div class="button-row"><button class="primary" id="trace-next">Follow line 1</button><button class="secondary" id="trace-reset">Start again</button></div><p class="demo-caption">This guide traces the displayed example. The Practice tab lets you run your own Python.</p>';
   const $=s=>host.querySelector(s);
   function draw(){const name=$('#demo-name').value;$('#trace-code').innerHTML='<div class="'+(step===1?'traced':'')+'"><span>1</span><code>name = '+esc(JSON.stringify(name))+'</code></div><div class="'+(step===2?'traced':'')+'"><span>2</span><code>print("Hello, " + name)</code></div>';$('#trace-name').textContent=step?JSON.stringify(name):'Not assigned yet';$('#trace-output').textContent=step===2?'Hello, '+name:'Nothing printed yet';$('#trace-status').textContent=step===0?'Before line 1. What do you predict?':step===1?'Line 1 gives the name a text value. It does not print anything.':'Line 2 joins the greeting and the remembered text, then displays the result.';$('#trace-next').disabled=step===2;$('#trace-next').textContent=step===0?'Follow line 1':step===1?'Follow line 2':'Both lines traced';}
   $('#trace-next').onclick=()=>{step=Math.min(2,step+1);draw();};$('#trace-reset').onclick=()=>{step=0;draw();};$('#demo-name').oninput=()=>{step=0;draw();};draw();return;
  }
  if(id==='sql-first'){
   const rows=[[1,'Asha','Jaipur'],[2,'Ravi','Bengaluru'],[3,'Meera','Chennai'],[4,'Kabir',null]],all=['id','name','city'];
   host.innerHTML=intro+'<h3>Choose the facts you want to see</h3><p>Each row describes one customer. Choosing a column changes which facts are shown.</p><div class="table-scroll"><table><caption>The four example customers</caption><thead><tr>'+all.map(c=>'<th scope="col">'+c+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x??'NULL')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><label for="demo-column">Which columns should the result show?</label><select id="demo-column"><option value="name">Only name</option><option value="city">Only city</option><option value="*">All three columns</option></select><pre id="demo-query"></pre><button class="primary" id="demo-select">Preview this result</button><div id="demo-table" class="demo-status" role="status" aria-live="polite">Predict the columns and how many rows you will see.</div><p class="demo-caption">This preview illustrates SELECT on the displayed table. The Practice tab runs your SQL in the browser. NULL marks a missing value.</p>';
   const $=s=>host.querySelector(s);function update(){const choice=$('#demo-column').value;$('#demo-query').textContent='SELECT '+choice+' FROM customers ORDER BY id;';$('#demo-table').textContent='Predict the columns and how many rows you will see.';}
   $('#demo-column').onchange=update;$('#demo-select').onclick=()=>{const choice=$('#demo-column').value,columns=choice==='*'?all:[choice];$('#demo-table').innerHTML='<p>Four rows. '+(choice==='*'?'All three facts for each customer.':'Only the '+choice+' fact for each customer.')+'</p><div class="table-scroll"><table><caption>Your selected result</caption><thead><tr>'+columns.map(c=>'<th scope="col">'+c+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+columns.map(c=>'<td>'+esc(row[all.indexOf(c)]??'NULL')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';};update();return;
  }
  if(id==='sf-map'){
   const cards=[{text:'Make the club form require a member name.',answer:'rules',why:'This changes the form rule for future records. Salesforce calls app rules and setup metadata.'},{text:'Mark one club member as present today.',answer:'record',why:'This changes one saved record. Other members and the form rule stay the same.'},{text:'Add a House field to the club form.',answer:'rules',why:'This changes the app structure, so it is metadata. Filling that field for one member would change a record.'}];let index=0;
   host.innerHTML=intro+'<h3>One record or the rules for everyone?</h3><p>Imagine a school club app. A record holds one member’s facts. Metadata describes the app’s fields and rules.</p><p id="club-question" class="club-question"></p><div class="demo-choices"><button class="secondary" data-kind="record">Change one saved record</button><button class="secondary" data-kind="rules">Change app fields or rules</button></div><p id="club-feedback" class="demo-status" role="status" aria-live="polite">Choose what this action changes.</p><button class="secondary" id="club-next">Try the next example</button><p class="demo-caption">These are fictional examples for understanding the idea. They do not change a Salesforce account.</p>';
   const $=s=>host.querySelector(s);function draw(){$('#club-question').textContent=cards[index].text;$('#club-feedback').textContent='Choose what this action changes.';host.querySelectorAll('[data-kind]').forEach(b=>b.classList.remove('demo-right','demo-retry'));}
   host.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{const correct=b.dataset.kind===cards[index].answer;b.classList.add(correct?'demo-right':'demo-retry');$('#club-feedback').textContent=(correct?'You’ve got it. ':'Try thinking about who is affected. ')+cards[index].why;});$('#club-next').onclick=()=>{index=(index+1)%cards.length;draw();};draw();return;
  }
  host.remove();
 }
 return {mount};
})();


// Teaching interactions never award lesson completion or inspect external tools.
window.TeachingBlocks=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(key,b){if(!b)return '';const id='teach-'+esc(key);return '<section class="first-step-demo teaching-block" data-teaching="'+esc(key)+'"><div class="eyebrow">ONE BUILDING BLOCK AT A TIME</div><h3>Understand before you build</h3><p>'+esc(b.idea||b.before)+'</p><pre class="code-block teaching-example"><code>'+esc(b.example||b.worked)+'</code></pre><h4>Follow the reasoning</h4><ol class="steps teaching-trace">'+(b.trace||b.steps).map((t,i)=>'<li '+(i?'hidden':'')+'>'+esc(t)+'</li>').join('')+'</ol><div class="button-row"><button class="secondary" data-trace-next>Reveal the next step</button><button class="quiet-button" data-trace-reset>Start the trace again</button></div><p class="teaching-trace-status" role="status"></p><fieldset><legend>'+esc(b.question)+'</legend><div class="demo-choices">'+b.choices.map((c,i)=>'<button class="secondary" data-teaching-answer="'+i+'">'+esc(c)+'</button>').join('')+'</div></fieldset><p class="teaching-feedback" role="status">Predict first. A warm-up answer does not complete the chapter.</p><details class="teaching-change"><summary>Try a small change, then compare</summary><label for="'+id+'">Write your prediction or attempt</label><textarea id="'+id+'" maxlength="2000" rows="3" placeholder="What would change? Explain your reasoning."></textarea><button class="secondary" data-teaching-compare>Compare with the guide</button><p class="teaching-change-feedback" role="status"></p><p class="teaching-change-guide" hidden>'+esc(b.try||b.guided)+'</p></details>'+(b.independent?'<details><summary>Independent challenge and test cases</summary><p>'+esc(b.independent)+'</p><p>Try without the worked example, then compare your actual result with these expected results. Record the evidence in the chapter activities below.</p></details>':'')+(b.boundary?'<p class="notice"><strong>Where to test this:</strong> '+esc(b.boundary)+'</p>':'')+'</section>';}
 function bind(root,blocks){root.querySelectorAll('[data-teaching]').forEach(el=>{const b=blocks[el.dataset.teaching];if(!b||el.dataset.teachingBound)return;el.dataset.teachingBound='true';const lines=[...el.querySelectorAll('.teaching-trace li')],next=el.querySelector('[data-trace-next]'),status=el.querySelector('.teaching-trace-status');let count=1;const update=()=>{lines.forEach((l,i)=>l.hidden=i>=count);next.disabled=count>=lines.length;status.textContent='Step '+count+' of '+lines.length+'. Read the reason before continuing.';};next.onclick=()=>{count=Math.min(count+1,lines.length);update();};el.querySelector('[data-trace-reset]').onclick=()=>{count=1;update();};update();el.querySelectorAll('[data-teaching-answer]').forEach(btn=>btn.onclick=()=>{el.querySelector('.teaching-feedback').textContent=(Number(btn.dataset.teachingAnswer)===b.correct?'Correct. ':'Try again. ')+b.feedback+' This warm-up does not award progress.';});el.querySelector('[data-teaching-compare]').onclick=()=>{const attempted=el.querySelector('textarea').value.trim();el.querySelector('.teaching-change-feedback').textContent=attempted?'Compare your reasoning below. This is a thinking guide, not an automatic grade.':'Write a prediction or a small attempt first.';el.querySelector('.teaching-change-guide').hidden=!attempted;};});}
 return{render,bind};
})();
