'use strict';
window.LearningJourney = (()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let api,data,section='roadmap',selected=null;
 const $=s=>document.querySelector(s), s=()=>{const state=api.state();state.journey??={};for(const k of ['activities','reviews','projects','planner','reflections'])state.journey[k]??={};return state.journey;};
 const track=()=>data.tracks.find(t=>t.id===api.state().track)||data.tracks[0];
 const modules=()=>data.tracks.flatMap(t=>t.modules);
 const getModule=id=>modules().find(m=>m.id===id);
 const activity=a=>s().activities[a.id]||{};
 const evidenceReady=m=>m.activities.every(a=>activity(a).rating==='independent'&&activity(a).evidence?.trim().length>=1);
 const retention=m=>evidenceReady(m)&&(s().reviews[m.id]?.streak||0)>=2;
 const started=m=>m.activities.some(a=>activity(a).evidence?.trim());
 const label=m=>retention(m)?'Reviewed again':evidenceReady(m)?'Practice checked':started(m)?'In progress':'Ready to start';
 const due=()=>modules().filter(m=>evidenceReady(m)&&s().reviews[m.id]?.due<=Date.now());
 const heading=(eyebrow,title,description)=>`<div class="journey-heading"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div>`;
 const nav=()=>`<nav class="journey-nav" aria-label="Learning journey">${[['roadmap','The roadmap'],['today','Today’s session'],['projects','Project portfolio']].map(([id,title])=>`<button data-journey="${id}" class="${section===id?'primary':'secondary'}" ${section===id?'aria-current="page"':''}>${title}</button>`).join('')}</nav>`;
 function bind(){document.querySelectorAll('[data-journey]').forEach(b=>b.onclick=()=>open(b.dataset.journey));document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.module));document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>api.openLesson(b.dataset.lab));document.querySelectorAll('[data-recall]').forEach(b=>b.onclick=()=>review(b.dataset.recall));}
 function shell(body){api.app.innerHTML=`<div class="journey">${nav()}${body}</div>`;bind();}
 function open(which='roadmap'){section=which;selected=null;history.replaceState(null,'','#roadmap');api.activate();if(window.LearnerStore.canEdit())render();}
 function render(){if(selected){modulePage(getModule(selected));return;}if(section==='today')today();else if(section==='projects')projects();else roadmap();}
 function roadmap(){
  const t=track(),done=t.modules.filter(evidenceReady).length;
  const levels=t.levels.map((level,index)=>{
   const items=level.modules.map(getModule).filter(Boolean);
   const levelDone=items.filter(evidenceReady).length;
   const cards=items.map(m=>'<article class="module-card '+(evidenceReady(m)?'evidence-ready':'')+'"><div class="module-meta"><span>CHAPTER '+String(t.modules.indexOf(m)+1).padStart(2,'0')+'</span><span>'+esc(label(m))+'</span></div><h3>'+esc(m.title)+'</h3><p>'+esc(m.plain)+'</p><div class="module-bottom"><span class="state-pill">'+m.topics.length+' key ideas</span><button class="secondary" data-module="'+m.id+'">Start chapter →</button></div></article>').join('');
   return '<details class="path-level" '+(index===0?'open':'')+'><summary><span class="level-number">LEVEL '+(index+1)+'</span><span class="level-copy"><strong>'+esc(level.title)+'</strong><small>'+esc(level.description)+'</small></span><span class="level-count">'+levelDone+' / '+items.length+' tried</span></summary><div class="roadmap-grid">'+cards+'</div></details>';
  }).join('');
  shell(heading('YOUR BEGINNER-FRIENDLY PATH','Start from zero. Learn one idea at a time.',t.prerequisite+' '+t.promise)+
   '<section class="starter-welcome"><div><span class="eyebrow">NO RUSH · NO EXPERIENCE NEEDED</span><h2>'+esc(t.title)+'</h2><p>'+esc(t.promise)+'</p><p class="starter-reassurance">New words are explained. Try a small example, make a guess, and learn from what happens. You can repeat any chapter.</p></div><div class="starter-checklist"><strong>Your simple learning loop</strong><ol><li>Read one clear idea</li><li>See a small example</li><li>Try it in the browser</li><li>Explain it in your own words</li></ol></div></section>'+
   '<div class="journey-stats"><div><strong>'+t.modules.length+'</strong><span>short chapters</span></div><div><strong>'+done+'/'+t.modules.length+'</strong><span>chapter check-ins</span></div><div><strong>'+data.projects.filter(p=>p.track===t.id).length+'</strong><span>projects to build later</span></div></div>'+
   '<div class="section-title beginner-level-title"><h2>Choose a level</h2><span>Start with Level 1. Later levels stay open whenever you are ready.</span></div><div class="level-stack">'+levels+'</div>'+
   '<section class="journey-intro"><div><h2>When something feels difficult</h2><p>Pause. Read the example again. Change one small thing and predict what will happen. A wrong answer is useful information; it shows us what to practise next.</p></div><div><h3>What do the check-ins mean?</h3><p>They are reminders to review your own work, not grades or certificates. You can use the practice lab for an automatic check, then return here to save what you learned.</p><a href="'+esc(t.resource)+'" target="_blank" rel="noopener">Official reference for later ↗</a></div></section>');
 }
 function openModule(id){const m=getModule(id);if(!m)return;const t=data.tracks.find(t=>t.modules.includes(m));api.state().track=t.id;selected=id;api.activate();api.save();modulePage(m);window.scrollTo({top:0,behavior:'instant'});}
 function modulePage(m){
  const t=data.tracks.find(x=>x.modules.some(y=>y.id===m.id))||track();
  const index=t.modules.indexOf(m),next=t.modules[index+1],missing=m.prerequisites.map(getModule).filter(x=>x&&!evidenceReady(x)).slice(0,2);
  const activityHTML=m.activities.map((a,i)=>{
   const r=activity(a);
   return '<details class="activity-card chapter-task" '+(i===0?'open':'')+'><summary><span>TRY '+String(i+1).padStart(2,'0')+'</span><strong>'+esc(a.type)+'</strong><small>'+esc(r.rating==='independent'?'You marked this independent':r.rating==='retry'?'Ready for another try':'Open this small challenge')+'</small></summary><div class="chapter-task-body"><h3>Your challenge</h3><p>'+esc(a.prompt)+'</p><label class="field-label" for="evidence-'+a.id+'">Write what you tried, noticed or would change</label><textarea id="evidence-'+a.id+'" data-evidence="'+a.id+'" class="note-field" maxlength="16000" placeholder="Start with one sentence or a small example. You can return and add more later.">'+esc(r.evidence||'')+'</textarea><div class="activity-controls"><button class="secondary" data-compare="'+a.id+'">Show a helpful answer</button><span id="activity-status-'+a.id+'" role="status">'+(r.rating==='independent'?'Self-check: I can do this':r.rating==='retry'?'Self-check: practise again':'Your work is saved in this browser')+'</span></div><div id="criteria-'+a.id+'" '+(r.revealed?'':'hidden')+' class="review-standard"><h4>Compare your thinking</h4><p>'+esc(a.criteria)+'</p><p>This is a guide for checking your work, not a grade.</p><div class="button-row"><button class="secondary" data-rate="retry" data-activity="'+a.id+'">I want another try</button><button class="primary" data-rate="independent" data-activity="'+a.id+'">I can explain this</button></div></div></div></details>';
  }).join('');
  shell(heading('LEVEL '+m.level+' · '+esc(m.levelTitle),esc(m.title),'Take one small step at a time. Read the plain explanation, follow the example, then try a browser exercise. You can pause and come back whenever you like.')+
   (missing.length?'<div class="notice"><strong>Helpful earlier chapters:</strong> '+missing.map(p=>'<button class="text-button" data-module="'+p.id+'">'+esc(p.title)+'</button>').join(' · ')+' . These ideas can help if this chapter feels tricky.</div>':'')+
   '<section class="beginner-first"><div class="eyebrow">FIRST, THE SIMPLE IDEA</div><h2>What this chapter is about</h2><p class="plain-explanation">'+esc(m.plain)+'</p><div class="everyday-example"><span>PICTURE IT</span><p>'+esc(m.analogy)+'</p></div><details class="word-guide"><summary>New words, explained simply</summary><dl>'+m.terms.map(pair=>'<div><dt>'+esc(pair[0])+'</dt><dd>'+esc(pair[1])+'</dd></div>').join('')+'</dl></details></section>'+
   '<section class="chapter-example"><div><span class="eyebrow">WATCH A SMALL EXAMPLE</span><h2>See the idea in action</h2><p>'+esc(m.example)+'</p></div><details><summary>Go a little deeper</summary><p>'+esc(m.concept)+'</p><div class="topic-tags">'+m.topics.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div></details></section><div id="concept-explorer"></div>'+ 
   '<div class="lab-bridge beginner-lab"><div><strong>Try a guided browser activity</strong><p>A short, safe place to practise this topic. Your changes will not affect a real account or database.</p></div><button class="primary" data-lab="'+m.lab+'">Open the practice activity ↗</button></div>'+
   '<div class="section-title"><h2>Now try it yourself</h2><span>Open one challenge at a time. You can save and return later.</span></div><div class="activity-stack">'+activityHTML+'</div>'+
   '<section class="side-card module-reflection"><h2>Teach it back</h2><label for="module-reflection" class="field-label">How would you explain this idea to a friend? Write one thing you understand and one thing you still wonder about.</label><textarea id="module-reflection" class="note-field" maxlength="12000" placeholder="I used to think… Now I think… I want to practise…">'+esc(s().reflections[m.id]||'')+'</textarea><p id="module-state" role="status">'+moduleSummary(m)+'</p></section>'+
   '<div class="button-row chapter-navigation"><button class="secondary" data-journey="roadmap">Back to levels</button>'+(next?'<button class="primary" data-module="'+next.id+'">Next chapter: '+esc(next.title)+' →</button>':'<button class="primary" data-journey="projects">Explore the projects →</button>')+'</div>');
  window.ConceptExplorers.mount(m.id,$('#concept-explorer'));
  api.app.querySelectorAll('[data-evidence]').forEach(input=>input.oninput=()=>{const r=s().activities[input.dataset.evidence]??={};r.evidence=input.value;r.rating=null;r.updated=Date.now();api.save();$('#activity-status-'+input.dataset.evidence).textContent='Saved · compare your answer when ready';$('#module-state').textContent=moduleSummary(m);});
  api.app.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const id=b.dataset.compare,r=s().activities[id]??={};if((r.evidence||'').trim().length<1){$('#activity-status-'+id).textContent='Try a word, a short answer or a small example first.';$('#evidence-'+id).focus();return;}r.revealed=true;$('#criteria-'+id).hidden=false;api.save();});
  api.app.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const id=b.dataset.activity,r=s().activities[id]??={};if((r.evidence||'').trim().length<1)return;r.rating=b.dataset.rate;r.updated=Date.now();$('#activity-status-'+id).textContent=r.rating==='retry'?'Saved · try again whenever you like':'Saved · you marked this as understood';if(evidenceReady(m)&&!s().reviews[m.id])s().reviews[m.id]={due:Date.now()+86400000,streak:0,interval:1};api.save();$('#module-state').textContent=moduleSummary(m);});
  $('#module-reflection').oninput=e=>{s().reflections[m.id]=e.target.value;api.save();};
 }
 function moduleSummary(m){const n=m.activities.filter(a=>activity(a).rating==='independent').length;return evidenceReady(m)?'You worked through all four activities. Come back later and see what you remember.':n+' of 4 activities marked as understood. Go at your own pace.';}
 function today(){
  const t=track(),m=t.modules.find(m=>!evidenceReady(m))||t.modules.at(-1),minutes=Number(s().planner.minutes||45),days=Number(s().planner.days||5),ready=due(),recall=Math.round(minutes*.2),build=Math.round(minutes*.6),reflect=minutes-recall-build;
  shell(`${heading('ONE DELIBERATE SESSION','Know what to do next.','A sustainable plan combines recall, new work and reflection. Finish one meaningful piece; you do not need to finish a module in one sitting.')}<section class="planner-card"><div><h2>Your weekly rhythm</h2><p>Adjust the pace to your real schedule. Plans and estimates update immediately.</p></div><label>Minutes per session<select id="session-minutes">${[20,30,45,60,90].map(n=>`<option ${n===minutes?'selected':''}>${n}</option>`).join('')}</select></label><label>Sessions per week<select id="session-days">${[2,3,4,5,6,7].map(n=>`<option ${n===days?'selected':''}>${n}</option>`).join('')}</select></label></section><div class="session-grid"><article class="session-card"><span class="eyebrow">01 / ${recall} MINUTES</span><h2>Retrieve</h2><p>${ready.length?`${ready.length} modules are ready for a delayed recall. Start with the oldest.`:'No module recall is due. Predict the next example without looking, or revisit a completed foundation lab.'}</p>${ready.length?`<button class="primary" data-recall="${ready.sort((a,b)=>s().reviews[a.id].due-s().reviews[b.id].due)[0].id}">Start delayed recall</button>`:`<button class="secondary" data-module="${m.id}">Try a prediction</button>`}</article><article class="session-card featured"><span class="eyebrow">02 / ${build} MINUTES</span><h2>Build & test</h2><p>Your next module: <strong>${esc(m.title)}</strong>. Work on the first unfinished activity. Use a tiny example before a bigger one.</p><button class="primary" data-module="${m.id}">Continue my path →</button></article><article class="session-card"><span class="eyebrow">03 / ${reflect} MINUTES</span><h2>Close the loop</h2><p>Write one corrected misconception, one example you can now explain, and your next smallest step.</p><label for="session-log" class="field-label">Session reflection</label><textarea id="session-log" class="note-field" maxlength="12000" placeholder="Today I thought… I tested… Now I understand…">${esc(s().reflections.session||'')}</textarea></article></div><section class="side-card"><h2>Your retention queue</h2><p>Recall is scheduled after 1, 3, 7, 14 and 30 days as self-reported recall improves. A difficult recall returns tomorrow. Early practice does not count as delayed retention.</p><div class="retention-list">${modules().filter(evidenceReady).map(m=>{const r=s().reviews[m.id];return `<div><span><strong>${esc(m.title)}</strong><small>${r?new Date(r.due).toLocaleDateString(): 'Not scheduled'} · ${r?.streak||0} successful delayed recalls</small></span><button class="secondary" data-recall="${m.id}">${r?.due<=Date.now()?'Recall now':'Practice early'}</button></div>`;}).join('')||'<p>Complete and self-review all four activities in a module to schedule its first recall.</p>'}</div></section>`);
  for(const [id,key] of [['session-minutes','minutes'],['session-days','days']])$('#'+id).onchange=e=>{s().planner[key]=Number(e.target.value);api.save();today();};
  $('#session-log').oninput=e=>{s().reflections.session=e.target.value;api.save();};
 }
 function review(id){
  const m=getModule(id),record=s().reviews[id],isDue=Boolean(record&&record.due<=Date.now());selected=null;
  const index=(record?.streak||0)%m.activities.length,a=m.activities[index];
  shell(`${heading(isDue?'DELAYED RECALL':'EARLY PRACTICE',esc(m.title),'Close your notes. Try the prompt from memory, then compare your reasoning. Be honest about help you needed.')}<section class="activity-card"><h2>${esc(a.prompt)}</h2><label for="recall-response" class="field-label">Your explanation or solution from memory</label><textarea id="recall-response" class="note-field" maxlength="16000"></textarea><button id="recall-reveal" class="primary">Compare my recall</button><p id="recall-feedback" role="status"></p><div id="recall-standard" hidden class="review-standard"><h3>Review standard</h3><p>${esc(a.criteria)}</p><div class="button-row"><button class="secondary" data-recall-grade="again">Needed help</button><button class="primary" data-recall-grade="remembered">Recalled independently</button></div><p>${isDue?'Your next recall date will reflect this self-assessment.':'This is early practice. It will not advance the delayed-retention marker.'}</p></div></section>`);
  $('#recall-reveal').onclick=()=>{if($('#recall-response').value.trim().length<30){$('#recall-feedback').textContent='Try an explanation first (at least 30 characters).';return;}$('#recall-standard').hidden=false;};
  api.app.querySelectorAll('[data-recall-grade]').forEach(b=>b.onclick=()=>{if($('#recall-standard').hidden)return;if(isDue){const success=b.dataset.recallGrade==='remembered',streak=success?(record.streak||0)+1:0,interval=success?data.reviewDays[Math.min(streak,data.reviewDays.length-1)]:1;s().reviews[id]={streak,interval,due:Date.now()+interval*86400000,lastResponse:$('#recall-response').value,lastReviewed:Date.now()};api.save();}open('today');});
 }
 function projects(){
  const t=track();shell(`${heading('BUILD A BODY OF WORK','Your evidence portfolio.','Projects bring several concepts together. Save the artifact location, test evidence and a short design explanation. Ask a peer to reproduce your work when possible.')}<div class="project-list">${data.projects.filter(p=>p.track===t.id).map((p,i)=>{const r=s().projects[p.id]||{};return `<article class="project-card"><div class="eyebrow">PROJECT 0${i+1} · AFTER ${esc(getModule(p.after).title)}</div><h2>${esc(p.title)}</h2><p>${esc(p.brief)}</p><label class="field-label" for="artifact-${p.id}">Artifact location and reproduction notes</label><textarea id="artifact-${p.id}" class="note-field" data-artifact="${p.id}" maxlength="12000" placeholder="Repository or local folder, setup steps, test commands, and a summary of your contribution. Never include credentials.">${esc(r.artifact||'')}</textarea><h3>Review the evidence</h3>${p.rubric.map((criterion,i)=>`<label class="project-criterion"><input type="checkbox" data-project="${p.id}" data-criterion="${i}" ${r.checks?.[i]?'checked':''}><span>${esc(criterion)}</span></label>`).join('')}<p id="project-status-${p.id}" role="status">${projectStatus(p,r)}</p><button class="secondary" data-module="${p.after}">Review preparation module</button></article>`;}).join('')}</div><p class="notice">Portfolio readiness is self-assessed. A checked rubric is not an automated code review, professional certification or independent evaluation.</p>`);
  api.app.querySelectorAll('[data-artifact]').forEach(input=>input.oninput=()=>{const r=s().projects[input.dataset.artifact]??={};r.artifact=input.value;api.save();$('#project-status-'+input.dataset.artifact).textContent=projectStatus(data.projects.find(p=>p.id===input.dataset.artifact),r);});
  api.app.querySelectorAll('[data-project]').forEach(input=>input.onchange=()=>{const r=s().projects[input.dataset.project]??={};r.checks??={};r.checks[input.dataset.criterion]=input.checked;api.save();$('#project-status-'+input.dataset.project).textContent=projectStatus(data.projects.find(p=>p.id===input.dataset.project),r);});
 }
 function projectStatus(p,r){return (r.artifact||'').trim().length>=40&&p.rubric.every((_,i)=>r.checks?.[i])?'Ready for peer review · self-assessed':'In progress · add reproducible evidence and review each criterion.';}
 function importBackup(input){
  if(!input||typeof input!=='object')return;
  for(const m of modules()){
   for(const a of m.activities){const r=input.activities?.[a.id];if(r&&typeof r.evidence==='string'&&r.evidence.length<=16000)s().activities[a.id]={evidence:r.evidence,rating:['independent','retry'].includes(r.rating)?r.rating:null,revealed:r.revealed===true};}
   const r=input.reviews?.[m.id];if(r&&Number.isFinite(r.due)&&Number.isInteger(r.streak)&&r.streak>=0&&r.streak<=1000&&Number.isFinite(r.interval)&&r.interval>=1&&r.interval<=30)s().reviews[m.id]={due:r.due,streak:r.streak,interval:r.interval};
  }
  for(const key of [...modules().map(m=>m.id),'session'])if(typeof input.reflections?.[key]==='string'&&input.reflections[key].length<=12000)s().reflections[key]=input.reflections[key];
  for(const p of data.projects){const r=input.projects?.[p.id];if(r&&typeof r.artifact==='string'&&r.artifact.length<=12000)s().projects[p.id]={artifact:r.artifact,checks:Object.fromEntries(p.rubric.map((_,i)=>[i,r.checks?.[i]===true]))};}
  if([20,30,45,60,90].includes(input.planner?.minutes))s().planner.minutes=input.planner.minutes;
  if([2,3,4,5,6,7].includes(input.planner?.days))s().planner.days=input.planner.days;
 }
 return {async init(bridge){api=bridge;const r=await fetch('academy/journey.json?v=9');if(!r.ok)throw Error('Roadmap could not load');data=await r.json();},open,render,importBackup,reset(){selected=null;section='roadmap';},hasData:()=>Boolean(data)};
})();
